### PR TITLE
Use binary keys for all fixtures

### PR DESCRIPTION
**Pull request by mupkoo**

### CODE REVIEW

**Comment by dylanjha** [comment]
@mupkoo thanks for the PR

Can you elaborate on what the purpose is behind this proposed change?

**Comment by mupkoo** [comment]
The fact that the library comes with fixture is super useful, but the responses that come from Tesla, are always with binary keys, which makes the fixtures with atom keys not really usable. 

And there were just a few fixtures that were using atom keys as well, which in a way improves the consistency.

**Comment by mupkoo** [comment]
Here is an example.
I use the fixture whenever I mock the requests, which is as easy as returning something like this

```elixir
%Tesla.Env{
  status: 201,
  body: %{"data" => Mux.Fixtures.live_stream()}
}
```

But this approach fails, for the fixtures that use atom keys, instead of binary ones. One more example

```elixir
defmodule App.MuxMock do
  @base_url "https://api.mux.com/video/v1"

  def mock() do
    Tesla.Mock.mock(&handler/1)
  end

  def mock_global() do
    Tesla.Mock.mock_global(&handler/1)
  end

  defp handler(%{method: :post, url: @base_url <> "/assets"}),
    do: %Tesla.Env{
      status: 201,
      body: %{"data" => Mux.Fixtures.asset()}
    }

  defp handler(%{method: :post, url: @base_url <> "/live-streams"}),
    do: %Tesla.Env{
      status: 201,
      body: %{"data" => Mux.Fixtures.live_stream()}
    }

  defp handler(%{method: :post, url: @base_url <> "/live-streams/live-stream-id/simulcast-targets"}),
    do: %Tesla.Env{
      status: 201,
      body: %{"data" => simulcast_target()}
    }

  @doc """
  Use until this is fixed upstream
  https://github.com/muxinc/mux-elixir/pull/31
  """
  def simulcast_target() do
    for {key, value} <- Mux.Fixtures.simulcast_target(), into: %{}, do: {"#{key}", value}
  end
end
```

**Comment by mmcc** [comment]
Oh wow, I was totally misreading this issue, yes, this is 100% an oversight and these fixtures are just straight up incorrect right now.

**Pull request merged**
