### PR TITLE
Change tesla dependency to >= 1.0.0

### PR DESCRIPTION
**Pull request by whitepaperclip**
We're using Tesla 1.3; afaik there aren't any breaking changes from 1.0 to 1.3, but it'd be good to avoid the hard requirement on using anything < 1.1

### CODE REVIEW

**Comment by dylanjha** [comment]
Thanks @whitepaperclip, looks good.

I'll be working on this library later this week so I'll check this change and see that it gets merged.

**Comment by whitepaperclip** [comment]
@dylanjha Thanks! There's actually one deprecation warning if you're using Tesla 1.3—just changing `Tesla.build_client` to `Tesla.client`. I could update that but the minimum version requirement would then be `>= 1.2`

**Comment by dylanjha** [comment]
I think what we want to do here is this:

1. Change the Tesla dep to `~> 1.2` (instead of `>= 1.2` - because we don't know if we'll be compatible with future _major_ releases like 2.0)
2. Update `Tesla.build_client` to `Tesla.client`

The other option would be to do `~> 1.0` and keep `Tesla.build_client` in the library code, but then we'd be putting out deprecation warnings and I don't really want to do that so I think we're okay bumping it up to `~> 1.2`.

Does that make sense? Unrelated to this change, I see in one other instance in our mix.exs file we're specifying `{:jason, ">= 1.0.0"},`, but I think we want to be using semvar here for the reason specified above.

**Comment by whitepaperclip** [comment]
@dylanjha `~> 1.2` still wouldn't allow users to use 1.3 unless they `override: true` in their `mix.exs`. If you wanted to, you could probably specify `{:tesla, ">= 1.0.0 and < 2.0.0"}` if there's some breaking change later?

There's no backwards compatibility issues between 1.0 and 1.3 other than the deprecation, so it probably wouldn't hurt to just require `~> 1.3`.

**Comment by dylanjha** [comment]
>  ~> 1.2 still wouldn't allow users to use 1.3 unless they override: true in their mix.exs.

Are you sure about that? I think that would be true if it was `~> 1.2.0` but `~> 1.2` should be what we want.

Example from the docs:

| ~>        | Translation           |
---------|-----------------| 
| ~> 2.0.0      | >= 2.0.0 and < 2.1.0 |
| ~> 2.1      | >= 2.1.0 and < 3.0.0      |

I'll double check, but that's how I believe these semvar dependencies work.

**Comment by whitepaperclip** [comment]
@dylanjha Whoops! You're right. I didn't realize the current mix was `~> 1.0.0` — anything will do, then.

**Comment by dylanjha** [comment]
@whitepaperclip thanks! I just double-checked in a real application to make sure I wasn't losing my mind, okay glad we're on the same page now.

If you feel like updating this PR with the two changes I mentioned above then I will try to get it merged tomorrow. I would prefer to do `~> 1.2` instead of `~> 1.3` to keep it more flexible in case a user's application has a different dependency that also depends on Tesla but that dependency is defined in a way that prevents them from bumping up from `1.2` to `1.3`.

Thanks!

**Comment by whitepaperclip** [comment]
@dylanjha Cool, thanks! Should be good to go.

**Pull request merged**
