### PR TITLE
Adding user-agent header

### PR DESCRIPTION
**Pull request by JacquiManzi**
Adding a user agent header to our Tesla Client.

### CODE REVIEW

**Review by jsanford8 — APPROVED** [review]
assuming this works, the code lgtm

**Review by philcluff — CHANGES_REQUESTED** [review]
Sorry to nit, but let's keep this consistent with the other server-side SDKs, and use `Mux Elixir`

**Comment by jsanford8** [comment]
Okay so we have a handful of things out there, we should decide what we want to conform to and make that happen. The formats we have so far are:

```
Mux <language> | <version>
OpenAPI-Generator/<version>/<language>
Mux/JS <version>
```

Should we just make everything conform to `Mux <language> | <version>`?

**Comment by philcluff** [comment]
IMO yes, there was a point in time where they were all aligned, but they've diverged :(

**Comment by jsanford8** [comment]
works for me

**Review by jsanford8 — APPROVED** [review]

**Pull request merged**
